"""Add foreign key to Personnel

Revision ID: 0f5698853697
Revises: 9af86dbfc976
Create Date: 2024-10-17 10:30:20.780968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5698853697'
down_revision = '9af86dbfc976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_personnels')
    with op.batch_alter_table('personnels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('squad_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_personnels_role_id_', 'roles', ['role_id'], ['role_id'])
        batch_op.create_foreign_key('fk_personnels_squad_id', 'squads', ['squad_id'], ['squad_id'])
        batch_op.create_foreign_key('fk_personnels_unit_id', 'units', ['unit_id'], ['unit_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personnels', schema=None) as batch_op:
        batch_op.drop_constraint('fk_personnels_role_id_roles', type_='foreignkey')
        batch_op.drop_constraint('fk_personnels_squad_id', type_='foreignkey')
        batch_op.drop_constraint('fk_personnels_unit_id', type_='foreignkey')
        batch_op.drop_column('squad_id')
        batch_op.drop_column('role_id')
        batch_op.drop_column('unit_id')

    op.create_table('_alembic_tmp_personnels',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('rank', sa.VARCHAR(length=30), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('joining_date', sa.DATETIME(), nullable=False),
    sa.Column('last_update', sa.DATETIME(), nullable=False),
    sa.Column('unit_id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('squad_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name='fk_personnel_role'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.squad_id'], name='fk_personnel_squad'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.unit_id'], name='fk_personnel_unit'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
