"""created units table

Revision ID: 723bd86da3b0
Revises: d2b79a0925b3
Create Date: 2024-10-15 18:03:04.001022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723bd86da3b0'
down_revision = 'd2b79a0925b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('unit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_name', sa.String(length=10), nullable=False),
    sa.Column('unit_type', sa.Enum('Navy', 'Army', 'Air Force', 'Marines'), nullable=False),
    sa.Column('unit_location', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('unit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units')
    # ### end Alembic commands ###
