"""created squads table

Revision ID: 76eba4612114
Revises: e8f2df3586ed
Create Date: 2024-10-15 23:39:07.538936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76eba4612114'
down_revision = 'e8f2df3586ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('squads',
    sa.Column('squad_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('squad_name', sa.String(length=100), nullable=False),
    sa.Column('squad_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('squad_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('squads')
    # ### end Alembic commands ###
