"""creates drop requests class

Revision ID: c344aad040c5
Revises: 76eba4612114
Create Date: 2024-10-16 00:02:37.994004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c344aad040c5'
down_revision = '76eba4612114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('droprequest',
    sa.Column('drop_request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drop_request_location', sa.String(length=50), nullable=False),
    sa.Column('drop_request_time', sa.Integer(), nullable=False),
    sa.Column('drop_request_description', sa.String(length=200), nullable=False),
    sa.Column('drop_request_status', sa.Enum('Pending', 'Approved', 'Rejected', name='drop_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('drop_request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('droprequest')
    # ### end Alembic commands ###
