"""Add foreign key to Squad

Revision ID: c3e87cef0c4e
Revises: 0f5698853697
Create Date: 2024-10-17 11:38:49.527297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e87cef0c4e'
down_revision = '0f5698853697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_squads_unit_id', 'units', ['unit_id'], ['unit_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('squads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_squads_unit_id', type_='foreignkey')
        batch_op.drop_column('unit_id')

    # ### end Alembic commands ###
